"""Created table

Revision ID: e7ee5c81e13d
Revises: 97c2cd9bc65f
Create Date: 2023-09-23 23:55:13.044184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ee5c81e13d'
down_revision = '97c2cd9bc65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baked_goods', sa.Column('bakery_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_baked_goods_bakery_id_bakeries'), 'baked_goods', 'bakeries', ['bakery_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_baked_goods_bakery_id_bakeries'), 'baked_goods', type_='foreignkey')
    op.drop_column('baked_goods', 'bakery_id')
    # ### end Alembic commands ###
